#!/usr/bin/env node

// Переписать нахрен в единый файл Javascript,
// который будет генерировать и agenda.json и presentations.json

var presentations =
[
  {key: '2',
    speaker: 'Dmitry Kostyuk',
    position: 'Бесменный ведущий',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Kostyuk.jpg'},
    name:  'Opening and closing speech',
    description: '',
    slideshare: '',
  },
  {key: '3',
    speaker: 'Eugene Pilyankevich',
    position: 'CTO, CEO Cossack Labs UA',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Pilyankevich.jpg'},
    name:  'Developing open-source security tooling: lessons to learn',
    description: '',
    slideshare: '',

  },
  {key: '4',
    speaker: 'Ihor Dvoretskyi',
    position: 'CNCF/LINUX foundation ambassador',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Dvoretskyi.jpg'},
    name: 'Driving open-source Software Products',
    description: '',
    slideshare: '',
  },
  {key: '5',
    speaker: 'Ignat Korchagin',
    position: 'Systems Engineer at CloudFlare, UK',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Korchagin.jpg'},
    name: 'Reclaim back keys for your kingdom: an open-source vaultless password manager',
    description: '',
    slideshare: '',
  },
  {key: '6',
    speaker: 'Denis Dovgopoliy',
    position: 'Investor, enterpreneur / founder at GrowthUP group',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Dovgopoliy.jpg'},
    name: 'Как слепить MVP продукта из говна и палок используя опенсорс решения или почему нельзя писать самому код ?',
    description: '',
    slideshare: '',
  },
  {key: '7',
    speaker: 'Stanislav Ivaschenko',
    position: 'Senior devops at Provectus',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Ivaschenko.jpg'},
    name: 'Jenkins',
    description: '',
    slideshare: '',
  },
  {key: '8',
    speaker: 'Viktor Turskyi',
    position: 'CTO at WebbyLab',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Turskyi.jpg'},
    name: 'Language Independent Validation Rules 2.0',
    description: '',
    slideshare: '',
  },
  {key: '9',
    speaker: 'Vladimir Melnik',
    position: 'CTO at Cloud Service Provider Tucha',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Melnik.jpg'},
    name: 'Построение неубиваемого кластера управления Apache CloudStack',
    description: '',
    slideshare: '',
  },
  {key: '10',
    speaker: 'Mykyta Biliavskyi',
    position: 'Lead Engineer at Samsung Electronics',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Biliavskyi.jpg'},
    name: 'Typical mistakes when submitting a new code to Linux kernel',
    description: '',
    slideshare: '',
  },
  {key: '11',
    speaker: 'Oleksii Kirichenko',
    position: 'Architect at GigaCloud',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Kirichenko.jpg'},
    name: 'How to build an openstack commercial cloud in less than 6 months',
    description: '',
    slideshare: '',
  },
  {key: '12',
    speaker: 'Evgeniy Fedirets',
    position: 'Translator, Contributor, QA, PR at Openorienteering',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Fedirets.jpg'},
    name: 'Openorienteering mapper: Довгий шлях до 1.0',
    description: '',
    slideshare: '',
  },
  {key: '13',
    speaker: 'Pavel Suikov',
    position: 'Developer at GlobalLogic',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Suikov.jpg'},
    name: 'Где я? The art of navigating by the GPS.',
    description: '',
    slideshare: '',
  },
  {key: '21',
    speaker: 'Vadim Getmanshchuk',
    position: 'Systems Engineer at Fastly Inc., USA',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Getmanshchuk.jpg'},
    name: 'Controlling your global web cache',
    description: '',
    slideshare: '',
  },
  {key: '22',
    speaker: 'Timofey Turenko',
    position: 'QA Engineer at MariaDB, Finland',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Turenko.jpg'},
    name: 'DB proxy server testing: run tests on tens of VMs with Jenkins, Vagrant and our tool MDBCI',
    description: '',
    slideshare: '',
  },
  {key: '24',
    speaker: 'Maxim Boguk',
    position: 'Chied DBA at Data Egret, Australia',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Boguk.jpg'},
    name: 'Неклассические техники оптимизации запросов в PostgreSQL, или как научить слона танцевать рок-н-ролл?',
    description: '',
    slideshare: '',
  },
  {key: '25',
    speaker: 'Roman Savochenko',
    position: '',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Savochenko.jpg'},
    name: 'OpenSCADA - відкрита SCADA система у перспективах релізу 0.9LTS',
    description: '',
    slideshare: '',
  },
  {key: '26',
    speaker: 'Mykola Marzhan',
    position: 'Release Engineer at Percona',
    photo: {uri: 'https://radetsky.github.io/app-osdn-org-ua-website/images/speakers/Marzhan.jpg'},
    name: 'Percona Monitoring and Management Architecture',
    description: '',
    slideshare: '',
  },
];

console.log(JSON.stringify(presentations));
